services:
  npm:
    container_name: floriday-npm
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
  pgsql:
    image: postgres:15
    container_name: floriday-pgsql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: floriday
      POSTGRES_USER: floriday
      POSTGRES_PASSWORD: secretFloriday
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app:/app
    restart: unless-stopped

volumes:
  pgdata:
  node_modules: